train: ./OID/train/images
val: ./OID/val/images

nc: 90
names:
  [
    "Bánh mì que",
    "Táo",
    "Atisô",
    "Măng tây",
    "Bánh mì vòng",
    "Bánh nướng",
    "Chuối",
    "Bia",
    "Ớt chuông",
    "Bánh mì",
    "Bông cải xanh",
    "Bánh burrito",
    "Bắp cải",
    "Bánh kem",
    "Kẹo",
    "Dưa vàng",
    "Cà rốt",
    "Quả sung",
    "Bánh quy",
    "Món tráng miệng",
    "Khoai tây chiên",
    "Nho",
    "Guacamole",
    "Bánh mì que",
    "Kem",
    "Bánh muffin",
    "Cam",
    "Bánh kếp",
    "Lê",
    "Bắp rang bơ",
    "Bánh quy xoắn",
    "Dâu tây",
    "Cà chua",
    "Bánh quế",
    "Đồ ăn và đồ uống",
    "Phô mai",
    "Cocktail",
    "Cà phê",
    "Chai xịt nấu ăn",
    "Cua",
    "Bánh sừng bò",
    "Dưa chuột",
    "Bánh vòng ngọt",
    "Trứng",
    "Trái cây",
    "Bưởi",
    "Hamburger",
    "Tổ ong mật",
    "Nước ép",
    "Chanh",
    "Tôm hùm",
    "Xoài",
    "Sữa",
    "Nấm",
    "Hàu",
    "Mì ống",
    "Bánh ngọt",
    "Đào",
    "Dứa",
    "Pizza",
    "Lựu",
    "Khoai tây",
    "Bí ngô",
    "Củ cải",
    "Salad",
    "Đồ ăn",
    "Bánh mì sandwich",
    "Tôm",
    "Bí",
    "Mực",
    "Bánh mì tàu ngầm",
    "Sushi",
    "Taco",
    "Bánh tart",
    "Trà",
    "Rau củ",
    "Dưa hấu",
    "Rượu vang",
    "Bí đông",
    "Bí xanh",
    "Bánh mì",
    "Bánh tráng trộn",
    "Bánh xèo",
    "Bún bò Huế",
    "Bún đậu",
    "Cơm tấm",
    "Gỏi cuốn",
    "Phở",
    "Hủ tiếu",
    "Xôi"
  ]

model:
name: YOLO11
args:
  max_det: 300 
data:
  dataloader:
    name: DataLoader
    args:
      batch_size: 1
      drop_last: False
      shuffle: False